---
 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springtest
  labels:
    app: yangyshdan-web
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: yangyshdan-web
    spec:
      containers:
        - name: springtest
          image: registry.cn-hangzhou.aliyuncs.com/fuyi-yy/springtest:1.0
          ports:
            - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: springtest
  labels:
    app: yangyshdan-web
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 9092
    nodePort: 30100
    protocol: TCP
    name: http
  selector:
    app: yangyshdan-web