---
 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springtest
  labels:
    app: yangyshdan-web
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: yangyshdan-web
    spec:
      containers:
      - name: springtest
        image: registry.cn-hangzhou.aliyuncs.com/fuyi-yy/springtest:1.0
        ports:
        - containerPort: 8080
        env:
        - name: JAEGER_SERVICE_NAME
          value: springtest
        - name: JAEGER_AGENT_HOST
          value: simplest-agent.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: springtest
  labels:
    app: yangyshdan-web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30100
    protocol: TCP
    name: http
  selector:
    app: yangyshdan-web