---
 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springtest
  labels:
    app: yangyshdan-web
    monitor: prometheus-actuator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yangyshdan-web
        monitor: k8s-prometheus
    spec:
      containers:
      - name: springtest
        image: registry.cn-hangzhou.aliyuncs.com/fuyi-yy/springtest
        ports:
        - containerPort: 8080
        env:
        - name: JAEGER_SERVICE_NAME
          value: springtest
        - name: JAEGER_AGENT_HOST
          value: simplest-agent.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: springtest
  labels:
    app: yangyshdan-web
    monitor: prometheus-actuator
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30100
    protocol: TCP
    name: http
  selector:
    app: yangyshdan-web